<?php

declare(strict_types=1);

namespace iggyvolz\html\Element;

/**
 * @autogenerated
 * Document body
 * @see https://html.spec.whatwg.org/#the-body-element
 * Categories: sectioning root
 * Parents: html
 * Children: flow
 * Attributes: globals,onafterprint,onbeforeprint,onbeforeunload,onhashchange,onlanguagechange,onmessage,onmessageerror,onoffline,ononline,onpagehide,onpageshow,onpopstate,onrejectionhandled,onstorage,onunhandledrejection,onunload
 */
final class BodyElement extends \iggyvolz\html\Element
{
    public const ELEMENT_NAME = 'body';

    /**
     * @param list<\iggyvolz\html\Element|string> $children
     */
    public function __construct(
        array $children,
        ?string $accesskey = null,
        ?string $autocapitalize = null,
        ?string $autofocus = null,
        ?string $contenteditable = null,
        ?string $dir = null,
        ?string $draggable = null,
        ?string $enterkeyhint = null,
        ?string $hidden = null,
        ?string $inputmode = null,
        ?string $is = null,
        ?string $itemid = null,
        ?string $itemprop = null,
        ?string $itemref = null,
        ?string $itemscope = null,
        ?string $itemtype = null,
        ?string $lang = null,
        ?string $nonce = null,
        ?string $spellcheck = null,
        ?string $style = null,
        ?string $tabindex = null,
        ?string $title = null,
        ?string $translate = null,
        ?string $onafterprint = null,
        ?string $onbeforeprint = null,
        ?string $onbeforeunload = null,
        ?string $onhashchange = null,
        ?string $onlanguagechange = null,
        ?string $onmessage = null,
        ?string $onmessageerror = null,
        ?string $onoffline = null,
        ?string $ononline = null,
        ?string $onpagehide = null,
        ?string $onpageshow = null,
        ?string $onpopstate = null,
        ?string $onrejectionhandled = null,
        ?string $onstorage = null,
        ?string $onunhandledrejection = null,
        ?string $onunload = null
    ) {
        $attributes = \array_filter([
            'accesskey' => $accesskey,
            'autocapitalize' => $autocapitalize,
            'autofocus' => $autofocus,
            'contenteditable' => $contenteditable,
            'dir' => $dir,
            'draggable' => $draggable,
            'enterkeyhint' => $enterkeyhint,
            'hidden' => $hidden,
            'inputmode' => $inputmode,
            'is' => $is,
            'itemid' => $itemid,
            'itemprop' => $itemprop,
            'itemref' => $itemref,
            'itemscope' => $itemscope,
            'itemtype' => $itemtype,
            'lang' => $lang,
            'nonce' => $nonce,
            'spellcheck' => $spellcheck,
            'style' => $style,
            'tabindex' => $tabindex,
            'title' => $title,
            'translate' => $translate,
            'onafterprint' => $onafterprint,
            'onbeforeprint' => $onbeforeprint,
            'onbeforeunload' => $onbeforeunload,
            'onhashchange' => $onhashchange,
            'onlanguagechange' => $onlanguagechange,
            'onmessage' => $onmessage,
            'onmessageerror' => $onmessageerror,
            'onoffline' => $onoffline,
            'ononline' => $ononline,
            'onpagehide' => $onpagehide,
            'onpageshow' => $onpageshow,
            'onpopstate' => $onpopstate,
            'onrejectionhandled' => $onrejectionhandled,
            'onstorage' => $onstorage,
            'onunhandledrejection' => $onunhandledrejection,
            'onunload' => $onunload,
        ], fn(?string $s) => !is_null($s));
        parent::__construct(self::ELEMENT_NAME, $attributes, $children);
    }
}
