<?php

declare(strict_types=1);

namespace iggyvolz\html\Element;

/**
 * @autogenerated
 * Form control
 * @see https://html.spec.whatwg.org/#the-input-element
 * Categories: flow,phrasing,interactive,listed,labelable,submittable,resettable,form-associated,palpable
 * Parents: phrasing
 * Children:
 * Attributes: globals,accept,alt,autocomplete,checked,dirname,disabled,form,formaction,formenctype,formmethod,formnovalidate,formtarget,height,list,max,maxlength,min,minlength,multiple,name,pattern,placeholder,readonly,required,size,src,step,type,value,width
 */
final class InputElement extends \iggyvolz\html\Element
{
    use \iggyvolz\html\VoidElement;

    public const ELEMENT_NAME = 'input';

    public function __construct(
        ?string $accesskey = null,
        ?string $autocapitalize = null,
        ?string $autofocus = null,
        ?string $contenteditable = null,
        ?string $dir = null,
        ?string $draggable = null,
        ?string $enterkeyhint = null,
        ?string $hidden = null,
        ?string $inputmode = null,
        ?string $is = null,
        ?string $itemid = null,
        ?string $itemprop = null,
        ?string $itemref = null,
        ?string $itemscope = null,
        ?string $itemtype = null,
        ?string $lang = null,
        ?string $nonce = null,
        ?string $spellcheck = null,
        ?string $style = null,
        ?string $tabindex = null,
        ?string $title = null,
        ?string $translate = null,
        ?string $accept = null,
        ?string $alt = null,
        ?string $autocomplete = null,
        ?string $checked = null,
        ?string $dirname = null,
        ?string $disabled = null,
        ?string $form = null,
        ?string $formaction = null,
        ?string $formenctype = null,
        ?string $formmethod = null,
        ?string $formnovalidate = null,
        ?string $formtarget = null,
        ?string $height = null,
        ?string $list = null,
        ?string $max = null,
        ?string $maxlength = null,
        ?string $min = null,
        ?string $minlength = null,
        ?string $multiple = null,
        ?string $name = null,
        ?string $pattern = null,
        ?string $placeholder = null,
        ?string $readonly = null,
        ?string $required = null,
        ?string $size = null,
        ?string $src = null,
        ?string $step = null,
        ?string $type = null,
        ?string $value = null,
        ?string $width = null
    ) {
        $children = [];
        $attributes = \array_filter([
            'accesskey' => $accesskey,
            'autocapitalize' => $autocapitalize,
            'autofocus' => $autofocus,
            'contenteditable' => $contenteditable,
            'dir' => $dir,
            'draggable' => $draggable,
            'enterkeyhint' => $enterkeyhint,
            'hidden' => $hidden,
            'inputmode' => $inputmode,
            'is' => $is,
            'itemid' => $itemid,
            'itemprop' => $itemprop,
            'itemref' => $itemref,
            'itemscope' => $itemscope,
            'itemtype' => $itemtype,
            'lang' => $lang,
            'nonce' => $nonce,
            'spellcheck' => $spellcheck,
            'style' => $style,
            'tabindex' => $tabindex,
            'title' => $title,
            'translate' => $translate,
            'accept' => $accept,
            'alt' => $alt,
            'autocomplete' => $autocomplete,
            'checked' => $checked,
            'dirname' => $dirname,
            'disabled' => $disabled,
            'form' => $form,
            'formaction' => $formaction,
            'formenctype' => $formenctype,
            'formmethod' => $formmethod,
            'formnovalidate' => $formnovalidate,
            'formtarget' => $formtarget,
            'height' => $height,
            'list' => $list,
            'max' => $max,
            'maxlength' => $maxlength,
            'min' => $min,
            'minlength' => $minlength,
            'multiple' => $multiple,
            'name' => $name,
            'pattern' => $pattern,
            'placeholder' => $placeholder,
            'readonly' => $readonly,
            'required' => $required,
            'size' => $size,
            'src' => $src,
            'step' => $step,
            'type' => $type,
            'value' => $value,
            'width' => $width,
        ], fn(?string $s) => !is_null($s));
        parent::__construct(self::ELEMENT_NAME, $attributes, $children);
    }
}
