<?php

declare(strict_types=1);

namespace iggyvolz\html\Element;

/**
 * @autogenerated
 * Link metadata
 * @see https://html.spec.whatwg.org/#the-link-element
 * Categories: metadata,flow,phrasing
 * Parents: head,noscript,phrasing
 * Children:
 * Attributes: globals,href,crossorigin,rel,as,media,hreflang,type,sizes,imagesrcset,imagesizes,referrerpolicy,integrity,blocking,color,disabled
 */
final class LinkElement extends \iggyvolz\html\Element
{
    use \iggyvolz\html\VoidElement;

    public const ELEMENT_NAME = 'link';

    public function __construct(
        ?string $accesskey = null,
        ?string $autocapitalize = null,
        ?string $autofocus = null,
        ?string $contenteditable = null,
        ?string $dir = null,
        ?string $draggable = null,
        ?string $enterkeyhint = null,
        ?string $hidden = null,
        ?string $inputmode = null,
        ?string $is = null,
        ?string $itemid = null,
        ?string $itemprop = null,
        ?string $itemref = null,
        ?string $itemscope = null,
        ?string $itemtype = null,
        ?string $lang = null,
        ?string $nonce = null,
        ?string $spellcheck = null,
        ?string $style = null,
        ?string $tabindex = null,
        ?string $title = null,
        ?string $translate = null,
        ?string $class = null,
        ?string $id = null,
        ?string $slot = null,
        ?string $href = null,
        ?string $crossorigin = null,
        ?string $rel = null,
        ?string $as = null,
        ?string $media = null,
        ?string $hreflang = null,
        ?string $type = null,
        ?string $sizes = null,
        ?string $imagesrcset = null,
        ?string $imagesizes = null,
        ?string $referrerpolicy = null,
        ?string $integrity = null,
        ?string $blocking = null,
        ?string $color = null,
        ?string $disabled = null
    ) {
        $children = [];
        $attributes = \array_filter([
            'accesskey' => $accesskey,
            'autocapitalize' => $autocapitalize,
            'autofocus' => $autofocus,
            'contenteditable' => $contenteditable,
            'dir' => $dir,
            'draggable' => $draggable,
            'enterkeyhint' => $enterkeyhint,
            'hidden' => $hidden,
            'inputmode' => $inputmode,
            'is' => $is,
            'itemid' => $itemid,
            'itemprop' => $itemprop,
            'itemref' => $itemref,
            'itemscope' => $itemscope,
            'itemtype' => $itemtype,
            'lang' => $lang,
            'nonce' => $nonce,
            'spellcheck' => $spellcheck,
            'style' => $style,
            'tabindex' => $tabindex,
            'title' => $title,
            'translate' => $translate,
            'class' => $class,
            'id' => $id,
            'slot' => $slot,
            'href' => $href,
            'crossorigin' => $crossorigin,
            'rel' => $rel,
            'as' => $as,
            'media' => $media,
            'hreflang' => $hreflang,
            'type' => $type,
            'sizes' => $sizes,
            'imagesrcset' => $imagesrcset,
            'imagesizes' => $imagesizes,
            'referrerpolicy' => $referrerpolicy,
            'integrity' => $integrity,
            'blocking' => $blocking,
            'color' => $color,
            'disabled' => $disabled,
        ], fn(?string $s) => !is_null($s));
        parent::__construct(self::ELEMENT_NAME, $attributes, $children);
    }
}
