<?php

declare(strict_types=1);

namespace iggyvolz\html\Element;

/**
 * @autogenerated
 * Multiline text controls
 * @see https://html.spec.whatwg.org/#the-textarea-element
 * Categories: flow,phrasing,interactive,listed,labelable,submittable,resettable,form-associated,palpable
 * Parents: phrasing
 * Children: text
 * Attributes: globals,cols,dirname,disabled,form,maxlength,minlength,name,placeholder,readonly,required,rows,wrap
 */
final class TextAreaElement extends \iggyvolz\html\Element
{
    use \iggyvolz\html\EscapableRawTextElement;

    public const ELEMENT_NAME = 'textarea';

    public function __construct(
        string $contents,
        ?string $accesskey = null,
        ?string $autocapitalize = null,
        ?string $autofocus = null,
        ?string $contenteditable = null,
        ?string $dir = null,
        ?string $draggable = null,
        ?string $enterkeyhint = null,
        ?string $hidden = null,
        ?string $inputmode = null,
        ?string $is = null,
        ?string $itemid = null,
        ?string $itemprop = null,
        ?string $itemref = null,
        ?string $itemscope = null,
        ?string $itemtype = null,
        ?string $lang = null,
        ?string $nonce = null,
        ?string $spellcheck = null,
        ?string $style = null,
        ?string $tabindex = null,
        ?string $title = null,
        ?string $translate = null,
        ?string $class = null,
        ?string $id = null,
        ?string $slot = null,
        ?string $cols = null,
        ?string $dirname = null,
        ?string $disabled = null,
        ?string $form = null,
        ?string $maxlength = null,
        ?string $minlength = null,
        ?string $name = null,
        ?string $placeholder = null,
        ?string $readonly = null,
        ?string $required = null,
        ?string $rows = null,
        ?string $wrap = null
    ) {
        $this->contents = $contents;
        $children = [];
        $attributes = \array_filter([
            'accesskey' => $accesskey,
            'autocapitalize' => $autocapitalize,
            'autofocus' => $autofocus,
            'contenteditable' => $contenteditable,
            'dir' => $dir,
            'draggable' => $draggable,
            'enterkeyhint' => $enterkeyhint,
            'hidden' => $hidden,
            'inputmode' => $inputmode,
            'is' => $is,
            'itemid' => $itemid,
            'itemprop' => $itemprop,
            'itemref' => $itemref,
            'itemscope' => $itemscope,
            'itemtype' => $itemtype,
            'lang' => $lang,
            'nonce' => $nonce,
            'spellcheck' => $spellcheck,
            'style' => $style,
            'tabindex' => $tabindex,
            'title' => $title,
            'translate' => $translate,
            'class' => $class,
            'id' => $id,
            'slot' => $slot,
            'cols' => $cols,
            'dirname' => $dirname,
            'disabled' => $disabled,
            'form' => $form,
            'maxlength' => $maxlength,
            'minlength' => $minlength,
            'name' => $name,
            'placeholder' => $placeholder,
            'readonly' => $readonly,
            'required' => $required,
            'rows' => $rows,
            'wrap' => $wrap,
        ], fn(?string $s) => !is_null($s));
        parent::__construct(self::ELEMENT_NAME, $attributes, $children);
    }
}
